services:
  - type: web
    name: student-helpdesk-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    region: ohio
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "false"
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://student-help-desk-sou.vercel.app,http://localhost:3000"
